<div class="add-user-wrapper">
	<div class="row">
		<div class="col-lg-6 col-lg-offset-3">
			<h2>Add New Announcement</h2>
			<form method="post" action="<?= $this->url('main-page', ['action' => 'add-announcement']) ?>">
				<div class="form-group">
		    		<label for="title">Title</label>
		    		<input type="text" name="title" class="form-control" id="title" placeholder="Enter title">
		  		</div>
		  		<div class="form-group">
		    		<label for="description">Description</label>
		    		<textarea rows="10" name="description" class="form-control" id="description" placeholder="Enter description"></textarea>
		  		</div>
			  	<button type="submit" class="btn btn-primary">Submit</button>
			</form>
		</div>
	</div>
</div>