<div class="add-user-wrapper">
	<div class="row">
		<div class="col-lg-4 col-lg-offset-4">
			<h2>Edit Teller</h2>
			<form method="post" action="<?= $this->url('main-page', ['action'=>'edit-teller', 'id' => $id]) ?>">
				<div class="form-group">
		    		<label for="teller">Teller / Window Name</label>
		    		<input type="text" name="name" value="<?= $teller['name'] ?>" class="form-control" id="teller" placeholder="Enter name">
		  		</div>
		  		<div class="form-group">
				    <label class="control-label" for="rolename">Accepted Transactions</label>
			        <select id="dates-field2" name="transactions[]" class="multiselect-ui form-control" multiple="multiple" required>
			        	<?php foreach ($transactions as $transaction): ?>
				        	<?php
				        		$teller_transactions = explode(',', $teller['transactions']);
				        		$selected = '';
				        		if (in_array($transaction['id'], $teller_transactions)) {
				        			$selected = "selected='selected'";
				        		}
				        	?>
				            <option value="<?= $transaction['id'] ?>" <?= $selected ?>><?= $transaction['name'] ?></option>
			            <?php endforeach; ?>
			        </select>
				</div>
		  		
			  	<button type="submit" class="btn btn-primary">Update Teller</button>
			  	<a href="<?= $this->url('main-page', ['action' => 'manage-teller']) ?>" type="submit" class="btn btn-default">Cancel</a>
			</form>
		</div>
	</div>
</div>

<script type="text/javascript">
$(function() {
    $('.multiselect-ui').multiselect({
        includeSelectAllOption: true
    });
});
</script>