<div class="table-responsive">
  <h2>List of Transactions</h2>
  <table class="table">
    <thead class="thead-inverse bg-primary">
      <tr>
        <th>ID #</th>
        <th>Transaction Name</th>
      </tr>
    </thead>
    <tbody>
        <?php if(!empty($transactions)): ?>
            <?php foreach ($transactions as $transaction): ?>
                <tr>
                    <th scope="row"><?= $transaction['id'] ?></th>
                    <td><?= $transaction['name'] ?></td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="2">No list Found</td>
            </tr>
        <?php endif; ?>
    </tbody>
  </table>
</div>