<div class="table-responsive">
  <h2>List of Users</h2>
  <table class="table">
    <thead class="thead-inverse bg-primary">
      <tr>
        <th>ID #</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Username</th>
        <th>Assigned Teller</th>
      </tr>
    </thead>
    <tbody>
        <?php if(!empty($users)): ?>
            <?php foreach ($users as $user): ?>
                <tr>
                    <th scope="row"><?= $user['id'] ?></th>
                    <td><?= $user['firstname'] ?></td>
                    <td><?= $user['lastname'] ?></td>
                    <td><?= $user['username'] ?></td>
                    <td><?= !empty($user['name']) ? $user['name'] : 'Not assigned' ?></td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="5">No Users Found</td>
            </tr>
        <?php endif; ?>
    </tbody>
  </table>
</div>