<div class="change-password-wrapper">
	<?php if (!empty($error)): ?>
       	<div class="alert alert-danger">
           	<p><?php echo $error ?></p>
        </div>
    <?php endif; ?>
    <?php if (!empty($success)): ?>
       	<div class="alert alert-success">
           	<p>You successfully change your password!</p>
        </div>
    <?php endif; ?>
	<div class="row">
		<div class="col-lg-6 col-lg-offset-3">
			<h2>Change Password</h2>
			<form method="post" action="<?= $this->url('guest-page', ['action' => 'change-password']) ?>">
				<div class="form-group">
		    		<label for="new_password">New Password</label>
		    		<input type="password" name="new_password" class="form-control" id="new_password" placeholder="" required>
		  		</div>
		  		<div class="form-group">
		    		<label for="confirm_password">Confirm Password</label>
		    		<input type="password" name="confirm_password" class="form-control" id="confirm_password" placeholder="" required>
		  		</div>
			  	<button type="submit" class="btn btn-primary">Update</button>
			</form>
		</div>
	</div>
</div>