<div class="customer-view-wrapper">
	<div class="row">
	    <div class="col-lg-12 text-center">
	    	<h1>Choose Your Priority Number</h1>
	    </div>
	</div>
	<div class="row">
	    <div class="col-lg-4 col-lg-offset-2">
	    	<a href="<?= $this->url('select-transaction', ['type' =>'guest']) ?>">
		      	<div class="tile green">
		        	<h3 class="title">Priority Number</h3>
		        	<p>Get your priority number by clicking this button.
		     	 </div>
		     </a>
	    </div>
	    <div class="col-lg-4">
	    	<a href="<?= $this->url('select-transaction', ['type' =>'senior']) ?>">
		      	<div class="tile blue">
		        	<h3 class="title">PWD's, Pregnant, Senior Citizen Priority Number</h3>
		        	<p>Click this button to get your PWD's, Pregnant, Senior Citizen Priority Number</p>
		      	</div>
		      </a>
	    </div>    
	</div>
</div>