<div class="container">
	<div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
			<?php if (!empty($error)): ?>
		       	<div class="alert alert-danger">
		           	<p><?php echo $error ?></p>
		        </div>
		    <?php endif; ?>
		</div>
	</div>
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
            <div class="account-wall">
                <div id="my-tab-content" class="tab-content">
					<div class="tab-pane active" id="login">
               		    <img class="profile-img" src="/img/avatar.png"
                    alt="">
               			<form class="form-signin" action="<?= $this->url('login') ?>" method="post">
               				<input type="text" name="username" class="form-control" placeholder="Username" required autofocus>
               				<input type="password" name="password" class="form-control" placeholder="Password" required>
               				<input type="submit" class="btn btn-lg btn-default btn-block" value="Sign In" />
               			</form>
					</div>
				</div>
            </div>
        </div>
    </div>
</div>